# Generated by Django 5.1.1 on 2024-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('Id_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('No_of_guests', models.CharField(max_length=100)),
                ('BookingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuTable',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Inventory', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
