# Generated by Django 5.1.1 on 2024-09-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtable',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='menutable',
            name='ID',
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menutable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
