# Generated by Django 5.1.1 on 2024-09-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_bookingtable_id_remove_menutable_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='id',
            new_name='ID_N',
        ),
        migrations.RenameField(
            model_name='menutable',
            old_name='id',
            new_name='ID_N',
        ),
    ]
