# Generated by Django 5.1.1 on 2024-09-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_id_bookingtable_id_n_rename_id_menutable_id_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='ID_N',
            new_name='Id_number',
        ),
    ]
